version: 'build #{build}'

before_build:

build_script:
  - gradlew build

after_build:
  - gradlew bintrayUpload
  - copy kotlin-sqlite\build\classes\kotlin\mingw\main\kotlin-sqlite-cinterop-sqlite3.klib sqlite3-mingw.klib
  - copy kotlin-sqlite\build\classes\kotlin\mingw\main\kotlin-sqlite.klib kotlin-sqlite-mingw.klib

artifacts:
  - path: sqlite3-mingw.klib
    name: interop
  - path: kotlin-sqlite-mingw.klib
    name: library

environment:
  BINTRAY_API_KEY:
    secure: 5NvV6wSGSu+wgrBkD+jQidMAJXDLwP6Ebz4Vjhkgm+Ok7okR+vG46ZJRsTB57/i5
