language: java

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - libsqlite3-dev
            - sqlite3
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sqlite3; fi

script:
  - ./gradlew build

after_success:
  - |
    ./gradlew bintrayUpload
  - |
    case "${TRAVIS_OS_NAME}" in
      osx)   export TARGET=macos ;;
      linux) export TARGET=linux ;;
      *)     exit 1 ;;
    esac
  - cp build/classes/kotlin/${TARGET}/main/kotlin-sqlite-cinterop-sqlite3.klib sqlite3-${TARGET}.klib
  - cp build/classes/kotlin/${TARGET}/main/kotlin-sqlite.klib kotlin-sqlite-${TARGET}.klib
