name: Build

on: [push]

jobs:
  build:
    name: 'Build'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: 'Clone Repo'
        uses: actions/checkout@v1

      - name: 'Build'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'build --stacktrace'

      - name: 'Publish to BinTray'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'smartPublish --stacktrace'
        if: startsWith(github.ref, 'refs/tags/')
        env:
          BINTRAY_API_KEY: ${{ secrets.bintray_api_key }}
          BINTRAY_USER: ${{ secrets.bintray_user }}
